name: Deploy S3 CI
on:
  pull_request:
    branches: [staging, main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.WEB_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.WEB_AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Move to docs folder
        run: mv build blogdocs && mkdir -p build && mv blogdocs build/docs

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: tempweb.getdozer.io
          bucket-region: ap-southeast-1
          delete-removed: true
          no-cache: true
          private: false
          filesToInclude: ".*/*,*/*,**"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Deployed at http://tempweb.getdozer.io.s3-website-ap-southeast-1.amazonaws.com/docs
